---

- name: List all Local Content Library
  vmware.vmware_rest.content_locallibrary_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: all_content_libraries

- name: Debug all_content_libraries
  ansible.builtin.debug:
    var: all_content_libraries

# - name: Use the name to identify the right Content Library
#   ansible.builtin.set_fact:
#     nfs_lib: "{{ all_content_libraries.value | selectattr('name', 'equalto', 'my_library_on_nfs')|first }}"

# - name: Get the list of items in the storage library
#   vmware.vmware_rest.content_library_item_info:
#     library_id:

# vmware.vmware_rest.vcenter_vm_info:
- name: Gather Template VM id
  vmware.vmware_rest.vcenter_vmtemplate_libraryitems_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    template_library_item: "{{ vcenter_config_template }}"
    # filter_names:
    #   - "{{ vcenter_config_template }}"
  register: template_vm

- name: Assert that Template VM was found
  ansible.builtin.assert:
    that:
      - template_vm.value | length > 0
    fail_msg: "Template VM '{{ vcenter_config_template }}' not found"
    success_msg: "Template VM '{{ vcenter_config_template }}' information retrieved"

- name: List VM templates
  vmware.vmware_rest.vcenter_vmtemplate_libraryitems_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    template_library_item: "*"
  register: existing_templates

- name: Debug existing_templates variable
  ansible.builtin.debug:
    var: existing_templates

#########################
# Content Library Section
- name: List all Local Content Library
  vmware.vmware_rest.content_locallibrary_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: all_content_libraries