---

- name: Validate pre-reqs available
  ansible.builtin.include_tasks:
    file: validate.yml

- name: Import Datacenter REST query
  ansible.builtin.include_tasks:
    file: set_dc.yml

- name: Import Cluster REST query
  ansible.builtin.include_tasks:
    file: set_cluster.yml

- name: Import Datastore REST query
  ansible.builtin.include_tasks:
    file: set_ds.yml

- name: Import Folder REST query
  ansible.builtin.include_tasks:
    file: set_folder.yml
  when: create_vsphere_vm_folder is defined

- name: Import Library REST query
  ansible.builtin.include_tasks:
    file: set_library.yml

- name: Import Library Item REST query
  ansible.builtin.include_tasks:
    file: set_library_item.yml

- name: List relevant facts gathered
  vars:
    msg: |
         Datacenter = '{{ create_vsphere_vm_datacenter }}'
         --------------------------
         Cluster Name = '{{ create_vsphere_vm_cluster }}'
         --------------------------
         Resource Pool = '{{ create_vsphere_vm_cluster_resource_pool }}'
         --------------------------
         Datastore = '{{ create_vsphere_vm_datastore }}'
         --------------------------
         Folder = '{{ create_vsphere_vm_folder | default(omit) }}'
         --------------------------
         Library Item Details
         {{ create_vsphere_vm_content_library_item | to_yaml }}
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"

- name: Import deploy vm from template
  ansible.builtin.include_tasks:
    file: deploy_vm_from_template.yml
  when: create_vsphere_vm_content_library_item.value.type == 'vm-template'

- name: Import deploy vm from ovf
  ansible.builtin.include_tasks:
    file: deploy_from_ovf.yml
  when: ( create_vsphere_vm_content_library_item.value.type == 'ovf'
          and not create_vsphere_vm_require_template )
      or ( create_vsphere_vm_content_library_item.value.type == 'ova'
          and not create_vsphere_vm_require_template)

- name: Start Virtual Machine
  ansible.builtin.include_tasks:
    file: start_vm.yml
  when: create_vsphere_vm_start_vm
