---

- name: set connection info
  ansible.builtin.set_fact:
    connection_args:
      vcenter_hostname: "{{ vcenter_hostname }}"
      vcenter_username: "{{ vcenter_username }}"
      vcenter_password: "{{ vcenter_password }}"
      vcenter_validate_certs: "{{ vcenter_validate_certs }}"

- name: List datacenters
  vmware.vmware_rest.vcenter_datacenter_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    filter_names:
      # Replace blank spaces with %20
      - "{{ create_vsphere_vm_datacenter | replace(' ', '%20') }}"
  register: _create_vsphere_vm_datacenter

- name: Debug datacenter info
  ansible.builtin.debug:
    var: _create_vsphere_vm_datacenter

- name: Build a list of all the clusters
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: _create_vsphere_vm_all_clusters

- name: Debug all the clusters info
  ansible.builtin.debug:
    var: _create_vsphere_vm_all_clusters

- name: Gather vmware Cluster id
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    filter_names:
      - "{{ create_vsphere_vm_cluster | replace(' ', '%20') }}"
  register: _create_vsphere_vm_my_cluster

- name: Show my_cluster_info
  ansible.builtin.debug:
    var: _create_vsphere_vm_my_cluster

- name: Gather vmware Cluster id
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    cluster: "{{ _create_vsphere_vm_my_cluster.value[0].cluster }}"
  register: _create_vsphere_vm_my_cluster_info

- name: Debug _create_vsphere_vm_my_cluster_info
  ansible.builtin.debug:
    var: _create_vsphere_vm_my_cluster_info

- name: Retrieve a list of all the datastores
  vmware.vmware_rest.vcenter_datastore_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: _create_vsphere_vm_all_datastores

- name: Show my_datastores
  ansible.builtin.debug:
    var: _create_vsphere_vm_all_datastores

- name: Build a list of all the folders
  vmware.vmware_rest.vcenter_folder_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: _create_vsphere_vm_all_folders

- name: Show all folders
  ansible.builtin.debug:
    var: _create_vsphere_vm_all_folders

- name: Gather folder information
  vmware.vmware_rest.vcenter_folder_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    filter_names:
      - "{{ create_vsphere_vm_folder | replace(' ', '%20') }}"
  register: _create_vsphere_vm_folder

- name: Show all folders
  ansible.builtin.debug:
    var: _create_vsphere_vm_folder

- name: Debug _create_vsphere_vm_my_cluster.id
  ansible.builtin.debug:
    var: _create_vsphere_vm_my_cluster.id

- name: Debug _create_vsphere_vm_datacenter.datastore
  ansible.builtin.debug:
    var: _create_vsphere_vm_datacenter.datastore

- name: Debug _create_vsphere_vm_folder.folder
  ansible.builtin.debug:
    var: _create_vsphere_vm_folder.folder

- name: _create_vsphere_vm_my_cluster_info.value.resource_pool
  ansible.builtin.debug:
    var: _create_vsphere_vm_my_cluster_info.value.resource_pool

- name: Create a VM
  vmware.vmware_rest.vcenter_vm:
    placement:
      cluster: "{{ _create_vsphere_vm_my_cluster.id }}"
      datastore: "{{ _create_vsphere_vm_datacenter.datastore }}"
      folder: "{{ _create_vsphere_vm_folder.folder }}"
      resource_pool: "{{ _create_vsphere_vm_my_cluster_info.value.resource_pool }}"
    name: test_vm1
    guest_OS: DEBIAN_8_64
    hardware_version: VMX_11
    memory:
      hot_add_enabled: true
      size_MiB: 1024
  register: _result
