---

- name: Retrieve a list of all the datastores
  vmware.vmware_rest.vcenter_datastore_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: _create_vsphere_vm_all_datastores

- name: Show my_datastores
  ansible.builtin.debug:
    var: _create_vsphere_vm_all_datastores
    verbosity: 2

- name: Retrieve a list of all the datastores
  vmware.vmware_rest.vcenter_datastore_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    filter_names:
      - "{{ create_vsphere_vm_datastore | urlencode }}"
  register: _create_vsphere_vm_my_datastore

- name: Show my_datastores
  ansible.builtin.debug:
    var: _create_vsphere_vm_my_datastore
    verbosity: 2

- name: Set Cluster fact vm_datastore
  ansible.builtin.set_fact:
    create_vsphere_vm_datastore: >
      "{{ _create_vsphere_vm_my_datastore.value[0].datastore }}"

- name: Debug fact set in Datastore gathering
  ansible.builtin.debug:
    var: create_vsphere_vm_datastore
    verbosity: 2
