---

- name: Build a list of all the clusters
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: _create_vsphere_vm_all_clusters

- name: Debug all the clusters info
  ansible.builtin.debug:
    var: _create_vsphere_vm_all_clusters
  when: create_vsphere_vm_debug

- name: Gather vmware Cluster id
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    filter_names:
      - "{{ create_vsphere_vm_cluster | replace(' ', '%20') }}"
  register: _create_vsphere_vm_my_cluster

- name: Show my_cluster_info
  ansible.builtin.debug:
    var: _create_vsphere_vm_my_cluster
  when: create_vsphere_vm_debug

- name: Gather vmware Cluster id
  vmware.vmware_rest.vcenter_cluster_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    cluster: "{{ _create_vsphere_vm_my_cluster.value[0].cluster }}"
  register: _create_vsphere_vm_my_cluster_info

- name: Debug _create_vsphere_vm_my_cluster_info
  ansible.builtin.debug:
    var: _create_vsphere_vm_my_cluster_info
  when: create_vsphere_vm_debug

- name: Set Cluster fact vm_cluster
  ansible.builtin.set_fact:
    create_vsphere_vm_cluster: "{{ _create_vsphere_vm_my_cluster_info.id }}"

- name: Set Cluster fact vm_cluster_resource_pool
  ansible.builtin.set_fact:
    create_vsphere_vm_cluster_resource_pool: "{{ _create_vsphere_vm_my_cluster_info.value.resource_pool }}"

- name: Debug fact set in cluster name gathering
  ansible.builtin.debug:
    var: create_vsphere_vm_cluster
  when: create_vsphere_vm_debug

- name: Debug fact set in cluster resource gathering
  ansible.builtin.debug:
    var: create_vsphere_vm_cluster_resource_pool
  when: create_vsphere_vm_debug
