---

- name: Debug datacenter name
  ansible.builtin.debug:
    var: create_vsphere_vm_datacenter
    verbosity: 2

- name: List datacenters
  vmware.vmware_rest.vcenter_datacenter_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    filter_names:
      # Replaces blank spaces with %20
      - "{{ create_vsphere_vm_datacenter | urlencode }}"
  register: _create_vsphere_vm_datacenter

- name: Debug datacenter info
  ansible.builtin.debug:
    var: _create_vsphere_vm_datacenter
    verbosity: 2

- name: Set Datacenter fact
  ansible.builtin.set_fact:
    create_vsphere_vm_datacenter: >
      "{{ _create_vsphere_vm_datacenter.value[0].datacenter }}"

- name: Debug fact set in datacenter gathering
  ansible.builtin.debug:
    var: create_vsphere_vm_datacenter
    verbosity: 2
