---

- name: Validate that required variables are provided
  ansible.builtin.assert:
    that:
      - vcenter_hostname is defined
      - vcenter_password is defined
      - vcenter_username is defined

- name: Validate python libraries
  community.general.python_requirements_info:
    dependencies:
      - aiohttp>=3.8
  register: _cv_pylib_available
  failed_when: >
    ( _cv_pylib_available.not_found is defined and
    _cv_pylib_available.not_found|length > 0 ) or
    (_cv_pylib_available.mismatched is defined and
    _cv_pylib_available.mismatched|length > 0)

- name: Debug python libraries
  ansible.builtin.debug:
    var: _cv_pylib_available
    verbosity: 2
